class CheckBoxLocators:
    EXPAND_ALL_BUTTON = "//button[@title='Expand all']"
    COLLAPSE_ALL_BUTTON = "//button[@title='Collapse all']"
    CHECKBOX_HOME = "//span[@class='rct-title' and text()='Home']"
    CHECKBOX_DESKTOP = "//span[@class='rct-title' and text()='Desktop']"
    CHECKBOX_NOTES = "//span[@class='rct-title' and text()='Notes']"
    CHECKBOX_COMMANDS = "//span[@class='rct-title' and text()='Commands']"
    CHECKBOX_DOCUMENTS = "//span[@class='rct-title' and text()='Documents']"
    CHECKBOX_WORKSPACE = "//span[@class='rct-title' and text()='WorkSpace']"
    CHECKBOX_REACT = "//span[@class='rct-title' and text()='React']"
    CHECKBOX_ANGULAR = "//span[@class='rct-title' and text()='Angular']"
    CHECKBOX_VEU = "//span[@class='rct-title' and text()='Veu']"
    CHECKBOX_DOWNLOADS = "//span[@class='rct-title' and text()='Downloads']"
    CHECKBOX_WORD_FILE = "//span[@class='rct-title' and text()='Word File.doc']"
    CHECKBOX_EXCEL_FILE = "//span[@class='rct-title' and text()='Excel File.doc']"
    OUTPUT_RESULT = "//div[@id='result']"